[project]
name = "md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9,<4.0"
dependencies = [
    "future>=1.0.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
    "typing-extensions>=4.15.0",
]
