name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[dev] || true  # if extras defined

      - name: Install lint tools
        run: pip install flake8

      - name: Lint
        run: flake8 mangadex

      - name: Test
        run: pytest --maxfail=1 --disable-warnings -q
